language: node_js
node_js:
  - "stable"
cache: yarn
before_install:
  - yarn
on:
  branch: master
script:
  - yarn tsc
  - yarn test
  - yarn build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "michaelgatesdev"
  - git config --local user.email "michaelgatesdev@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "961e6fa29898a4340c54e30a074ab104c8b7947c"
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
after_deploy:
  - echo "Deploy complete"