language: node_js
node_js:
  - "stable"
cache: yarn
before_install:
  - yarn
on:
  branch: master
script:
  - yarn test

deploy:
  provider: releases
  api_key: "e5eb4cb719656807587a869955b020a3c545c753"
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true