language: node_js
node_js:
  - "stable"
cache: yarn
before_install:
  - yarn
on:
  branch: master
script:
  - yarn tsc
  - yarn test
  - yarn build

deploy:
  provider: releases
  api_key: "961e6fa29898a4340c54e30a074ab104c8b7947c"
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true